### ISSUE TITLE
TTS - Reset command clarification

### ISSUE THREAD

**Issue by giomarino** [deepgram/deepgram-twilio-streaming-voice-agent#5]
In the server.js file, what is the purpose of the instruction.

`mediaStream.deepgramTTSWebsocket.send(JSON.stringify({ 'type': 'Reset' }));`

In what situations is the 'Reset' message type used? Where I could find information about it?

**Comment by dvonthenen** [comment]
If you are queueing up `Text` messages to be processed, the `Reset` will clear/reset the buffer on the server. Any text in the buffer will not be included in the audio generation.
